### PR TITLE
fix: Reject bid after delete should collect larger penalty

### LINKED ISSUE #91: Reject bid after payer delete
**Describe the bug**
If a payer rejects a bid after they delete their flow during the bid period, the depleted stream amount is taken from the bidder's collateral. 

**Expected behavior**
Instead, this should be added to the penalty payment owed by the payer.

### PR DESCRIPTION
**Pull request by codynhat**
# Description

Fixes #91 

# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `main` or appropriate feature branch
- [x] My PR is opened against the `main` or appropriate feature branch

### CODE REVIEW

**Comment by codynhat** [comment]
@gravenp As I've gone through the test cases, I think there is a different way to do this. Instead of having the payer pay more than the penalty, we could just no longer allow rejecting a bid if the payer deletes their flow. The bid period would immediately end and anyone can trigger a transfer.

So deleting your flow while there is a bid outstanding is the same as accepting the bid. Once it is deleted though, the depleting amount is taken from the for sale price the payer would receive. 

Thoughts?

**Comment by gravenp** [comment]
> @gravenp As I've gone through the test cases, I think there is a different way to do this. Instead of having the payer pay more than the penalty, we could just no longer allow rejecting a bid if the payer deletes their flow. The bid period would immediately end and anyone can trigger a transfer.
> 
> So deleting your flow while there is a bid outstanding is the same as accepting the bid. Once it is deleted though, the depleting amount is taken from the for sale price the payer would receive.
> 
> Thoughts?

If you're able to treat flow deletion effectively the same as a bid rejection window passing, that would simplify the accounting perspective for sure. Would we need to update the logic for the `Needs Transfer` window to look for something different?  We'd still want to add the messaging about the reduction of sales proceeds for the intervening `Network Fees` regardless.

From a user perspective, I don't think it's unfair/unexpected that you'd lose your right to reject a bid if your stream is stopped.

**Comment by codynhat** [comment]
Yes, I think that logic would need to be updated.

> We'd still want to add the messaging about the reduction of sales proceeds for the intervening Network Fees regardless.

Are you talking about https://github.com/Geo-Web-Project/cadastre/issues/242? They could be prompted to trigger a transfer if their stream is closed which will immediately stop the bleeding of their for sale price.

Another case here is if the user deletes their flow and then reopens it. I think we should still not allow them to reject if they reopen. There could be some vulnerabilities here where they can take funds from the bidder.

**Comment by gravenp** [comment]
Yeah that ticket wouldn't fully apply anymore, so I'd modify it to add the appropriate text on the screen with the Transfer Parcel button rather than the screen with the Accept +(disabled) Reject buttons.

As for reopening the stream, agreed. Once a stream has been cancelled, the ship has sailed. The user has forfeited their right to keep the parcel uninterrupted.

**Pull request merged**
